<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Create Call</title>
</head>

<style>
    select {
        padding: 10px 20px;
        border-radius: 5px;
        background-color: white;
        outline: none;
        font-family: "Courier New", Courier, monospace;
    }

    select:hover {
        transition-duration: 1s;
        background-color: lightgray;
        /* color: red; */
    }

    /* option:hover{
        transition-duration: 1s;
        background-color: black;
        color: white;
    } */

    option {
        padding: 10px 20px;
        background-color: white;
        outline: none;
        font-family: "Courier New", Courier, monospace;
    }

    .inputText {
        /* background-color: red; */
        border-top-color: transparent;
        border-left-color: transparent;
        border-right-color: transparent;
        outline: none;
    }

    body {
        font-family: sans-serif;
    }
</style>

<body>
    <section class="vh-100 bg-image" style="
        background-image: url('https://mdbcdn.b-cdn.net/img/Photos/new-templates/search-box/img4.webp');
      ">
        <div class="mask d-flex align-items-center h-100 gradient-custom-3">
            <div class="container h-100">
                <div class="row d-flex justify-content-center align-items-center h-100">
                    <div class="col-12 col-md-9 col-lg-7 col-xl-6">
                        <div class="card" style="border-radius: 15px">
                            <div class="card-body p-5">
                                <h2 class="text-center mb-5 text-info">Create Call Log</h2>

                                <?php
                                if (isset($msg)) {
                                    echo "<div class='h5 text-primary'>$msg</div>";
                                }
                                ?>
                                <form method="post">
                                    <!-- post data is done code the action  -->
                                    <!-- //Hidden Felids -->

                                    <input type="hidden" name="id" value=<?php echo $_GET['id'] ?>>
                                    <input type="hidden" name="username" value=<?php echo $_GET['username'] ?>>
                                    <input type="hidden" name="owner_id" value=<?php echo $_GET['owner_id'] ?>>
                                    <input type="hidden" name="objectType" value=<?php echo $_GET['objectType'] ?>>

                                    <div class="row">
                                        <div class="col">
                                            <div class="form-outline mb-4">
                                                <label class="form-label text-danger" for="form3Example1cg">Call Title</label>
                                                <input type="text" id="form3Example1cg" name="title" class="form-control form-control-lg inputText" />
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col">
                                            <div class="form-group">
                                                <label for="exampleFormControlTextarea1" class="text-danger">Call Description</label>
                                                <textarea class="form-control inputText" id="exampleFormControlTextarea1" name="description" rows="2"></textarea>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col">
                                            <div class="form-group">
                                                <label for="exampleFormControlTextarea1" class="text-danger">Call Duration</label>
                                                <input type="number" class="form-control inputText" id="exampleFormControlTextarea1" placeholder="in milliseconds" name="callDuration" rows="2"></input>
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col">
                                            <div class="form-outline mb-4">
                                                <label class="form-label text-danger" for="form3Example1cg">Call Recording Url</label>
                                                <input type="text" id="form3Example1cg" name="recordingURL" class="form-control form-control-lg inputText" />
                                            </div>
                                        </div>
                                    </div>

                                    <div class="row">
                                        <div class="col">
                                            <div class="form-outline mb-4">
                                                <div class="form-outline datetimepicker">
                                                    <label class="form-label text-danger" for="form3Example1cg">To Number</label>
                                                    <input type="number" class="form-control" name="toNumber" />
                                                </div>
                                            </div>
                                        </div>

                                        <div class="col">
                                            <label class="form-label text-danger" for="form3Example1cg">From Number</label>
                                            <input type="number" class="form-control" name="fromNumber" />
                                        </div>
                                    </div>


                                    <div class="row">
                                        <div class="col d-flex justify-content-center mb-3 mt-4">
                                            <select class="form-select" aria-label="Default select example" name="status">
                                                <option selected disabled>Select Call Status</option>
                                                <option value="NOT_STARTED">BUSY</option>
                                                <option value="CALLING_CRM_USER">Calling CRM User</option>
                                                <option value="CANCELED">Canceled</option>
                                                <option value="COMPLETED">Completed</option>
                                                <option value="CONNECTING">Connecting</option>
                                                <option value="FAILED">Failed</option>
                                                <option value="IN_PROGRESS">In Progress</option>
                                                <option value="NO_ANSWER">No Answer</option>
                                                <option value="QUEUED">Queued</option>
                                                <option value="RINGING">Ringing</option>
                                            </select>
                                        </div>
                                    </div>


                                    <div class="row">
                                        <div class="col d-flex justify-content-center mt-3">
                                            <button class="btn btn-outline-success btn-block btn-lg gradient-custom-4 text-body mt-4">
                                                Create
                                            </button>
                                        </div>
                                    </div>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
</body>

</html>