<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>

<style>
    .delBtn {

        font-size: 10px;
        padding: 5px 20px;
        /* float: right; */
        margin-left: 20px;

    }

    .taskDate {
        float: left;
    }

    .notesData {
        margin-top: 20px;
    }

    .cardTASK:hover .delBTN {
        transition-duration: 1s;
        color: green;
        background-color: red;
        text-emphasis-color: blue;
    }

    .overflowPPT {
        /* width: 100px; */
        max-height: 25rem;
        overflow-y: scroll;
    }
</style>

<body>


    <section style="background-color: #eee;">
        <div class="container py-5">

            <div class="row">
                <div class="col-lg-4">
                    <div class="card mb-4">
                        <div class="card-body text-center">
                            <img src="https://cdn-icons-png.flaticon.com/512/1458/1458201.png" alt="avatar" class="rounded-circle img-fluid" style="width: 150px;">
                            <h5 class="my-3">
                                <?php
                                if (isset($username)) {
                                    echo $username;
                                } else {
                                    echo "Data is not available";
                                }
                                ?>
                            </h5>
                            <p class="text-muted mb-1">Full Stack Developer</p>
                            <p class="text-muted mb-4">Bay Area, San Francisco, CA</p>
                            <div class="d-flex justify-content-center mb-2">
                                <!-- <button type="button" class="btn btn-primary">Follow</button>
                                <button type="button" class="btn btn-outline-primary ms-1">Message</button> -->
                            </div>
                        </div>
                    </div>
                    <div class="card mb-4 mb-lg-0">
                        <div class="card-body p-0">
                            <div class="h2 text-center text-primary font-bold font-weight-">Engagements</div>

                            <ul class="list-group list-group-flush rounded-3">

                                <form action="" method="post">

                                    <!-- Some Hidden Field to send data -->
                                    <input type="hidden" id='cid' name="id" value=<?php echo $user_id ?>>
                                    <input type="hidden" id='username' name="username" value=<?php echo $username ?>>
                                    <input type="hidden" id='emailID' name="email" value=<?php echo $email ?>>
                                    <input type="hidden" id='owner_id' name="owner_id" value=<?php echo $owner_id ?>>

                                    <!-- Notes     -->
                                    <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                        <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-journal-bookmark" viewBox="0 0 16 16">
                                            <path fill-rule="evenodd" d="M6 8V1h1v6.117L8.743 6.07a.5.5 0 0 1 .514 0L11 7.117V1h1v7a.5.5 0 0 1-.757.429L9 7.083 6.757 8.43A.5.5 0 0 1 6 8z" />
                                            <path d="M3 0h10a2 2 0 0 1 2 2v12a2 2 0 0 1-2 2H3a2 2 0 0 1-2-2v-1h1v1a1 1 0 0 0 1 1h10a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H3a1 1 0 0 0-1 1v1H1V2a2 2 0 0 1 2-2z" />
                                            <path d="M1 5v-.5a.5.5 0 0 1 1 0V5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0V8h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1zm0 3v-.5a.5.5 0 0 1 1 0v.5h.5a.5.5 0 0 1 0 1h-2a.5.5 0 0 1 0-1H1z" />
                                        </svg>
                                        <i class="bi bi-journal-bookmark"></i>
                                        <p class="mb-0"><button class="btn btn-outline-info pl-4 pr-4">Notes</button></p>
                                    </li>
                                </form>
                                <!-- Email    -->
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-envelope" viewBox="0 0 16 16">
                                        <path d="M0 4a2 2 0 0 1 2-2h12a2 2 0 0 1 2 2v8a2 2 0 0 1-2 2H2a2 2 0 0 1-2-2V4Zm2-1a1 1 0 0 0-1 1v.217l7 4.2 7-4.2V4a1 1 0 0 0-1-1H2Zm13 2.383-4.708 2.825L15 11.105V5.383Zm-.034 6.876-5.64-3.471L8 9.583l-1.326-.795-5.64 3.47A1 1 0 0 0 2 13h12a1 1 0 0 0 .966-.741ZM1 11.105l4.708-2.897L1 5.383v5.722Z" />
                                    </svg>
                                    <p class="mb-0"><button class="btn btn-outline-info  pl-4 pr-4" id="emailBTN">Email</button></p>
                                </li>

                                <!-- Task   -->
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-list-task" viewBox="0 0 16 16">
                                        <path fill-rule="evenodd" d="M2 2.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5V3a.5.5 0 0 0-.5-.5H2zM3 3H2v1h1V3z" />
                                        <path d="M5 3.5a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 0 1h-9a.5.5 0 0 1-.5-.5zM5.5 7a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9zm0 4a.5.5 0 0 0 0 1h9a.5.5 0 0 0 0-1h-9z" />
                                        <path fill-rule="evenodd" d="M1.5 7a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5H2a.5.5 0 0 1-.5-.5V7zM2 7h1v1H2V7zm0 3.5a.5.5 0 0 0-.5.5v1a.5.5 0 0 0 .5.5h1a.5.5 0 0 0 .5-.5v-1a.5.5 0 0 0-.5-.5H2zm1 .5H2v1h1v-1z" />
                                    </svg>
                                    <i class="bi bi-journal-bookmark"></i>
                                    <p class="mb-0"><button class="btn btn-outline-info  pl-4 pr-4 taskBTN">Task</button></p>
                                </li>

                                <!-- Meeting -->
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-alarm" viewBox="0 0 16 16">
                                        <path d="M8.5 5.5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9V5.5z" />
                                        <path d="M6.5 0a.5.5 0 0 0 0 1H7v1.07a7.001 7.001 0 0 0-3.273 12.474l-.602.602a.5.5 0 0 0 .707.708l.746-.746A6.97 6.97 0 0 0 8 16a6.97 6.97 0 0 0 3.422-.892l.746.746a.5.5 0 0 0 .707-.708l-.601-.602A7.001 7.001 0 0 0 9 2.07V1h.5a.5.5 0 0 0 0-1h-3zm1.038 3.018a6.093 6.093 0 0 1 .924 0 6 6 0 1 1-.924 0zM0 3.5c0 .753.333 1.429.86 1.887A8.035 8.035 0 0 1 4.387 1.86 2.5 2.5 0 0 0 0 3.5zM13.5 1c-.753 0-1.429.333-1.887.86a8.035 8.035 0 0 1 3.527 3.527A2.5 2.5 0 0 0 13.5 1z" />
                                    </svg>
                                    <i class="bi bi-journal-bookmark"></i>
                                    <p class="mb-0"><button class="btn btn-outline-info meetingBt">Meeting</button></p>
                                </li>

                                <!-- Call  -->
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-telephone" viewBox="0 0 16 16">
                                        <path d="M3.654 1.328a.678.678 0 0 0-1.015-.063L1.605 2.3c-.483.484-.661 1.169-.45 1.77a17.568 17.568 0 0 0 4.168 6.608 17.569 17.569 0 0 0 6.608 4.168c.601.211 1.286.033 1.77-.45l1.034-1.034a.678.678 0 0 0-.063-1.015l-2.307-1.794a.678.678 0 0 0-.58-.122l-2.19.547a1.745 1.745 0 0 1-1.657-.459L5.482 8.062a1.745 1.745 0 0 1-.46-1.657l.548-2.19a.678.678 0 0 0-.122-.58L3.654 1.328zM1.884.511a1.745 1.745 0 0 1 2.612.163L6.29 2.98c.329.423.445.974.315 1.494l-.547 2.19a.678.678 0 0 0 .178.643l2.457 2.457a.678.678 0 0 0 .644.178l2.189-.547a1.745 1.745 0 0 1 1.494.315l2.306 1.794c.829.645.905 1.87.163 2.611l-1.034 1.034c-.74.74-1.846 1.065-2.877.702a18.634 18.634 0 0 1-7.01-4.42 18.634 18.634 0 0 1-4.42-7.009c-.362-1.03-.037-2.137.703-2.877L1.885.511z" />
                                    </svg>
                                    <i class="bi bi-journal-bookmark"></i>
                                    <p class="mb-0"><button class="btn btn-outline-info  pl-4 pr-4 callBt">Call</button></p>
                                </li>

                            </ul>
                        </div>

                        <!-- ********************************Association********************************** -->
                        <div class="card-body p-0 mt-5">
                            <div class="h2 text-center text-primary font-bold font-weight-">Association</div>

                            <ul class="list-group list-group-flush rounded-3">

                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <div class="h4">Contact</div>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <div class="h4">Company</div>

                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <div class="h4">Ticket</div>
                                </li>
                                <li class="list-group-item d-flex justify-content-between align-items-center p-3">
                                    <div class="h4">Deals</div>

                                </li>
                            </ul>
                        </div>
                    </div>
                </div>


                <div class="col-lg-8">
                    <div class="card mb-4">
                        <div class="card-body">
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">User ID</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">
                                        <?php
                                        if (isset($user_id)) {
                                            echo $user_id;
                                        } else {
                                            echo "Data is not available";
                                        }
                                        ?>
                                    </p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Full Name</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">
                                        <?php
                                        if (isset($username)) {
                                            echo $username;
                                        } else {
                                            echo "Data is not available";
                                        }
                                        ?>
                                    </p>
                                </div>
                            </div>
                            <hr>
                            <div class="row">
                                <div class="col-sm-3">
                                    <p class="mb-0">Email</p>
                                </div>
                                <div class="col-sm-9">
                                    <p class="text-muted mb-0">
                                        <?php
                                        if (isset($email)) {
                                            echo $email;
                                        } else {
                                            echo "Data is not available";
                                        }
                                        ?>
                                    </p>
                                </div>
                            </div>
                            <hr>

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-md-6">
                            <div class="card mb-4 mb-md-0 overflowPPT">
                                <div class="card-body">
                                    <p class="mb-4 text-info"><span class="text-info font-italic me-1"></span>Notes
                                    </p>
                                    <ul class="list-group list-group-flush">
                                        <?php
                                        if (isset($notesHtml)) {
                                            echo $notesHtml;
                                        } else {
                                            echo "Data is not available";
                                        }
                                        ?>
                                    </ul>
                                </div>
                            </div>
                        </div>
                        <div class="col-md-6">
                            <div class="card mb-4 mb-md-0 overflowPPT">
                                <div class="card-body">
                                    <p class="mb-4 text-info"><span class="text-info font-italic me-1"></span>Emails
                                    </p>
                                    <?php
                                    if (isset($emailsHtml)) {
                                        echo $emailsHtml;
                                    } else {
                                        echo "Data is not available";
                                    }
                                    ?>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div class="row mt-4">
                        <div class="col-md-6">
                            <div class="card mb-4 mb-md-0 overflowPPT">
                                <div class="card-body">
                                    <p class="mb-4 text-info"><span class="text-info font-italic me-1"></span>Tasks
                                    </p>
                                    <div class="ml-5 ">

                                        <?php
                                        if (isset($taskhtml)) {
                                            echo $taskhtml;
                                        } else {
                                            echo "Data is not available";
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                        <div class="col-md-6">
                            <div class="card mb-4 mb-md-0 overflowPPT">
                                <div class="card-body">
                                    <p class="mb-4 text-info"><span class="text-info font-italic me-1"></span>Meetings
                                    </p>
                                    <div class="ml-5 ">

                                        <?php
                                        if (isset($meetingHTML)) {
                                            echo $meetingHTML;
                                        } else {
                                            echo "Data is not available";
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>

                    </div>
                    <div class="row mt-4">
                        <div class="col">
                            <div class="card mb-4 mb-md-0 overflowPPT ">
                                <div class="card-body">
                                    <p class="mb-4 text-info text-center"><span class="text-info font-italic me-1"></span>Call Logs
                                    </p>
                                    <div class="">

                                        <?php
                                        if (isset($callHTML)) {
                                            echo $callHTML;
                                        } else {
                                            echo "Data is not available";
                                        }
                                        ?>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>


                </div>
            </div>
        </div>
    </section>
</body>

<script>
    $(document).ready(function() {

        //global Variable

        $('.delBtn').click(function(e) {
            e.preventDefault();
            // console.log(this.value);

            //Del a Note

            $.ajax({
                type: "post",
                url: "https://remote.local.cedcommerce.com/hubspotremote/engagement/deleteNote?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ&username=kajal%20jaiswal&email=kajaljaiswal123@gmail.com&user_id=2501",
                data: {
                    'Did': this.value
                },
                success: function(response) {
                    console.log(response);
                    window.location.reload();
                }
            });


        });

        //Email Engagement 
        $('#emailBTN').click(function(e) {
            e.preventDefault();
            console.log("Email clicked");
            var objectID = $('#cid').val();
            var username = $('#username').val();
            var email = $('#emailID').val();
            var owner_id = $('#owner_id').val();

            // console.log(contactID);
            // console.log(username);
            // console.log(email);
            window.location.href = "https://remote.local.cedcommerce.com/hubspotremote/engagement/sendEmail?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ&username=" + username + "&email=" + email + "&id=" + objectID + "&owner_id=" + owner_id + "&objectType=" + "<?php echo $_GET['objectType']; ?>";

        });

        $('.emaildelBTN').click(function(e) {
            e.preventDefault();
            console.log("hello");
            $.ajax({
                type: "post",
                url: "https://remote.local.cedcommerce.com/hubspotremote/engagement/delEmails?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ&username=kajal%20jaiswal&email=kajaljaiswal123@gmail.com&user_id=2501",
                data: {
                    "id": this.value,
                    "EngagementType": "email"
                },
                success: function(response) {
                    console.log(response);
                    alert("Email Log Deleted");

                }
            });
        });

        //Task Engagement
        $('.taskBTN').click(function(e) {
            e.preventDefault();
            console.log("Task");
            var objectID = $('#cid').val();
            var username = $('#username').val();
            var email = $('#emailID').val();
            var owner_id = $('#owner_id').val();

            // console.log(contactID);
            // console.log(username);
            // console.log(email);
            window.location.href = "https://remote.local.cedcommerce.com/hubspotremote/engagement/createtask?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ&username=" + username + "&email=" + email + "&id=" + objectID + "&owner_id=" + owner_id + "&objectType=" + "<?php echo $_GET['objectType']; ?>";


        });

        //del task 
        $(".delTASKBTN").click(function(e) {
            e.preventDefault();
            console.log("del working");
            $.ajax({
                type: "post",
                url: "https://remote.local.cedcommerce.com/hubspotremote/engagement/delEngagement?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ&username=kajal%20jaiswal&email=kajaljaiswal123@gmail.com&user_id=2501",
                data: {
                    "id": this.value,
                    'EngagementType': 'task'
                },
                success: function(response) {
                    console.log(response);
                    alert("Task Deleted");


                }
            });
        });


        //Meeting Button
        $(".meetingBt").click(function(e) {
            e.preventDefault();
            console.log("Workinggg");
            var objectID = $('#cid').val();
            var username = $('#username').val();
            var email = $('#emailID').val();
            var owner_id = $('#owner_id').val();

            // console.log(contactID);
            // console.log(username);
            // console.log(email);
            window.location.href = "https://remote.local.cedcommerce.com/hubspotremote/engagement/createMeeting?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ&username=" + username + "&email=" + email + "&id=" + objectID + "&owner_id=" + owner_id + "&objectType=" + "<?php echo $_GET['objectType']; ?>";


        });


        $(".delMeetingBTN").click(function(e) {
            e.preventDefault();
            console.log("Meeting delete");
            $.ajax({
                type: "post",
                url: "https://remote.local.cedcommerce.com/hubspotremote/engagement/delEngagement?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ&username=kajal%20jaiswal&email=kajaljaiswal123@gmail.com&user_id=2501",
                data: {
                    "id": this.value,
                    'EngagementType': 'meeting'
                },
                success: function(response) {
                    console.log(response);
                    alert("Meeting Deleted");

                }
            });
        });

        //call log Button
        $(".callBt").click(function(e) {
            e.preventDefault();
            console.log("Workinggg");
            var objectID = $('#cid').val();
            var username = $('#username').val();
            var email = $('#emailID').val();
            var owner_id = $('#owner_id').val();

            // console.log(contactID);
            // console.log(username);
            // console.log(email);
            window.location.href = "https://remote.local.cedcommerce.com/hubspotremote/engagement/createCall?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ&username=" + username + "&email=" + email + "&id=" + objectID + "&owner_id=" + owner_id + "&objectType=" + "<?php echo $_GET['objectType']; ?>";


        });


        //del call log
        $('.delCallBTN').click(function(e) {
            e.preventDefault();
            console.log("working");
            e.preventDefault();
            console.log("Meeting delete");
            $.ajax({
                type: "post",
                url: "https://remote.local.cedcommerce.com/hubspotremote/engagement/delEngagement?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ&username=kajal%20jaiswal&email=kajaljaiswal123@gmail.com&user_id=2501",
                data: {
                    "id": this.value,
                    'EngagementType': 'call'
                },
                success: function(response) {
                    console.log(response);
                    alert("call log Deleted");

                }
            });
        });

    });
</script>

</html>