<?php
// echo "<pre>";
// print_r($this->request->getPost());
// echo "</pre>";
?>
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <title>Document</title>
</head>

<body class="">
    <h1 class="text-center text-primary">Update Line Item</h1>

    <?php

    if (isset($flag)) {

        echo '<div class="alert alert-success alert-dismissible fade show" role="alert">
        <strong>Company Registered</strong> One Company is Sucessfully Registered! Company ID = ' . $flag . '
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
        </button>
        </div>';
    }

    ?>


    <div class="container mt-5 mb-5 d-flex justify-content-center">
        <div class="card px-1 py-4">
            <!-- <div class="row">
                <div class="col">
                    <div class="h1 text-center">Message :<?php
                                                            // if (isset($flag)) {
                                                            //     echo $flag;
                                                            // }
                                                            ?> is Successfully Registered :)</div>
                </div> -->
            <!-- </div> -->
            <form action="" method="POST">

                <div class="card-body" style="padding: 30px;">
                    <h6 class="card-title mb-3 text-center">Update Line Item Details</h6>

                    <div class="row">
                        <div class="col-sm-12">
                            <!-- <div class="form-group">
                                <div class="input-group"> <input class="form-control" type="text" name="dealstage" placeholder="Deal Stage" required> </div>
                            </div> -->
                            <select class="form-select mb-3" id="products" aria-label="Default select example" required>
                                <option disabled selected>Choose Product</option>
                                <?php echo $data ?>
                            </select>
                        </div>
                    </div>

                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <!-- <label for="name">Name</label> --> <input class="form-control  qty" type="text" name="quantity" placeholder="quantity" required>
                            </div>
                        </div>
                    </div>
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="form-group">
                                <div class="input-group"> <input class="form-control amt" type="text" name="amount" placeholder="Amount" required> </div>
                            </div>
                        </div>
                    </div>

                    <input type="hidden" name="pipeline" value="default">

                    <button class="btn btn-primary btn-block confirm-button" id="saveBtn">Update</button>
                </div>
            </form>
        </div>

    </div>



</body>

<script>
    $(document).ready(function() {

        $('#saveBtn').click(function(e) {
            e.preventDefault();

            var productval=$("#products").val();
            var productInfo=productval.split(",");
            var product_id=productInfo[0];
            var product_name=productInfo[1];
            var amount = $('.amt').val();
            var quantity = $('.qty').val();

            $.ajax({
                type: "post",
                url: "",
                data: {
                    "productID": product_id,
                    "productName": product_name,
                    "amount": amount,
                    "quantity": quantity
                },
                success: function(response) {
                    console.log(response);
                }
            });
            console.log(product_id,product_name, amount, quantity);
        });
    });
</script>

</html>