<?php
//  echo $data;
//  die;
?>
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <style>
        table {
            /* padding: 10px; */
            border: 2px solid red;
            border-collapse: collapse;
            text-align: center;

        }

        /* tr:hover {
            transition-duration: 0.7s;
            /* background-color: black; */
        /* color: white; */
        /* border: 3px solid red; */
        /* transform: scale(1.05);
        border-radius: 2px;
        box-shadow: rgba(50, 50, 93, 0.25) 0px 30px 60px -12px inset,
        rgba(0, 0, 0, 0.3) 0px 18px 36px -18px inset; */

        /* } */

        /* td:hover {
            transition-duration: 0.7s;
            /* background-color: black; */
        /* color: white; */
        /* border: 3px solid red;
            transform: scale(1.1);
            border-radius: 10px;
            box-shadow: rgba(50, 50, 93, 0.25) 0px 30px 60px -12px inset, rgba(0, 0, 0, 0.3) 0px 18px 36px -18px inset; */

        /* } */

        /* td {
            border: 2px solid black;
        } */

        #ckbCheckAll {
            position: relative;
            left: 10px;
            font-size: 20px;
        }

        checkbox {
            font-size: 15px;
        }
    </style>
</head>

<body>
    <h1 class="text-center text-primary">Line Item Listing</h1>
    <div class="row mt-2 mb-2 mt-4">
        <div class="col d-flex justify-content-center">
            <button class="btn btn-outline-danger mr-2" id="removeBtn">Remove</button>
            <button class="btn btn-outline-success" id="Create Line"><a href="https://remote.local.cedcommerce.com/hubspotremote/line/add?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ" style="text-decoration:none; color:green">Create Deal</a></button>
        </div>
    </div>
    <table class="table  table-striped">
        <thead>
            <tr>
                <th class="text-info"> <input class='form-check-input checkBoxes' type='checkbox' id='ckbCheckAll'>
                </th>
                <th class="text-info">Line Item Id</th>
                <th class="text-info">Name</th>
                <th class="text-info">Price</th>
                <th class="text-info">Create Date</th>
                <th class="text-info">Product id</th>
                <th class="text-info">Quantity</th>
                <th class="text-info">Action</th>
            </tr>
        </thead>
        <tbody>
            <?php echo $data ?>
        </tbody>
    </table>
</body>
<script>
    $(document).ready(function() {
        console.log("working");

        $("#removeBtn").click(function(e) {
            e.preventDefault();
            if (confirm("Confirm to Delete!")) {
                var data = [];
                $('input[name="checkBoxvalues"]:checked').each(function() {
                    // console.log(this.value);
                    data.push(this.value);
                });

                $.ajax({
                    type: "post",
                    url: "https://remote.local.cedcommerce.com/hubspotremote/line/removeDataInBulk?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ",
                    data: {
                        'data': data
                    },
                    success: function(response) {
                        console.log(response);
                        location.reload();
                    }
                });
                console.log(data);
            } else {
                console.log("cancel");
            }

        });

        //Function to check all the checkboxes
        $("#ckbCheckAll").click(function() {
            $(".checkBoxes").attr('checked', this.checked);
        });
    });
</script>

</html>