<?php 
//  echo $data;
//  die;
?>
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
<style>

    table{
        /* padding: 10px; */
        border: 2px solid red;
        border-collapse:collapse;
        text-align: center;
        
    }  
    
    tr:hover{
        transition-duration: 0.7s;
        /* background-color: black; */
        /* color: white; */
        /* border: 3px solid red; */
        transform:scale(1.05);
        border-radius: 2px;
        box-shadow: rgba(50, 50, 93, 0.25) 0px 30px 60px -12px inset, rgba(0, 0, 0, 0.3) 0px 18px 36px -18px inset;
        
    }

    td:hover{
        transition-duration: 0.7s;
        /* background-color: black; */
        /* color: white; */
        /* border: 3px solid red; */
        transform:scale(1.1);
        border-radius: 10px;
        box-shadow: rgba(50, 50, 93, 0.25) 0px 30px 60px -12px inset, rgba(0, 0, 0, 0.3) 0px 18px 36px -18px inset;
        
    }
    td{
        border: 2px solid black;
    }

</style>
</head>

<body>
    <h1 class="text-center text-lead display-5 text-danger">Products Listing</h1>
    <table class="table  table-striped">
        <thead>
            <tr>
                <th class="text-info">Product ID</th>
                <th class="text-info">Product Name</th>
                <th class="text-info">Price</th>
                <th class="text-info">Created Date</th>
                <th class="text-info">Actions</th>
            </tr>
        </thead>
        <tbody>
          <?php  echo $data?>
        </tbody>
    </table>
</body>

</html>