<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<style>
    #searchBar {
        padding: 5px 10px;
        outline: none;
        border-radius: 10px;
        border: 2px solid black;
        font-family: 'Courier New', Courier;
        color: green;
        font-size: 20px;
        text-align: center;
    }

    #searchBar:focus {
        color: brown;
    }

    #searchBar:hover {
        transition-duration: 1s;
        border-radius: 0px;
    }

    select option {
        border: 1px solid steelblue;
        margin-top: 2px;
        text-align: center;
        border-radius: 5px;
    }

    select option:hover {
        transition-duration: 0.3s;
        background-color: steelblue;
        color: white;
        letter-spacing: 3px;
    }
</style>

<body>
    <div class="h1 text-center">Choose Custom Object Which you want to Perform Crud Operation</div>

    <div class="row mt-5">
        <div class="row d-flex justify-content-center mt-5">
            <div class="col-6 ">
                <div class="input-group d-flex justify-content-center">
                    <input type="search" class="" placeholder="Search Custom Object" id="searchBar" aria-label="Search" aria-describedby="search-addon" />
                    <!-- <button type="button" class="btn btn-outline-primary">search</button> -->
                </div>
            </div>
        </div>

        <div class="row d-flex justify-content-center mt-3">
            <div class="col-8">
                <select class="form-select form-select-sm selectForm" size="10" id="optionbar" aria-label="size 10 select example">\
                </select>
            </div>
        </div>
        <div class="row d-flex justify-content-center mt-3">
            <div class="col d-flex justify-content-center mt-3">
                <button class="btn btn-outline-success selectObject">Select</button>
                </select>
            </div>
        </div>
    </div>
</body>








<script>
    $(document).ready(function() {
        var CustomObjectData = [];
        // console.log("sd");
        //Ajax call to get all the data of custom object
        $.ajax({
            type: "post",
            url: "https://remote.local.cedcommerce.com/hubspotremote/crud/getCustomObjectData?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ",
            success: function(response) {
                var jsondata = JSON.parse(response);
                CustomObjectData = jsondata;
                console.log(jsondata);
            }
        });


        //Live Search
        $("#searchBar").keyup(function() {
            var str = "";
            for (var i = 0; i < CustomObjectData.results.length; i++) {

                if (CustomObjectData.results[i].name.match(this.value)) {
                    str += "<option value=" + CustomObjectData.results[i].objectTypeId + ">" + CustomObjectData.results[i].name + "</option>";
                }
            }

            $("#optionbar").html(str);

        });


        //Select an Event for Crud
        $('.selectObject').click(function(e) {
            e.preventDefault();
            var objectTypeID = $('#optionbar').val();
            var objectName = $('#optionbar option:selected').text();
            console.log("Object Name\n" + objectName);
            console.log("Object ID\n" + objectTypeID);
            if (objectTypeID !== 'undefined' && objectName !== 'undefined') {

                window.location = ("http://remote.local.cedcommerce.com/hubspotremote/crud/listingobjectitem?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ&objectTypeID=" + objectTypeID + "&ObjectName=" + objectName + "")
            } else {
                alert("Select An Option Please");
            }
        });
    });
</script>

</html>