<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <link href="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <style>
        .register {
            background: -webkit-linear-gradient(left, #3931af, #00c6ff);
            margin-top: 3%;
            padding: 3%;
        }

        .register-left {
            text-align: center;
            color: #fff;
            margin-top: 4%;
        }

        .register-left input {
            border: none;
            border-radius: 1.5rem;
            padding: 2%;
            width: 60%;
            background: #f8f9fa;
            font-weight: bold;
            color: #383d41;
            margin-top: 30%;
            margin-bottom: 3%;
            cursor: pointer;
        }

        .register-right {
            background: #f8f9fa;
            border-top-left-radius: 10% 50%;
            border-bottom-left-radius: 10% 50%;
        }

        .register-left img {
            margin-top: 15%;
            margin-bottom: 5%;
            width: 25%;
            -webkit-animation: mover 2s infinite alternate;
            animation: mover 1s infinite alternate;
        }

        @-webkit-keyframes mover {
            0% {
                transform: translateY(0);
            }

            100% {
                transform: translateY(-20px);
            }
        }

        @keyframes mover {
            0% {
                transform: translateY(0);
            }

            100% {
                transform: translateY(-20px);
            }
        }

        .register-left p {
            font-weight: lighter;
            padding: 12%;
            margin-top: -9%;
        }

        .register .register-form {
            padding: 10%;
            margin-top: 10%;
        }

        .btnRegister {
            float: right;
            margin-top: 10%;
            border: none;
            border-radius: 1.5rem;
            padding: 2%;
            background: #0062cc;
            color: #fff;
            font-weight: 600;
            width: 50%;
            cursor: pointer;
        }

        .register .nav-tabs {
            margin-top: 3%;
            border: none;
            background: #0062cc;
            border-radius: 1.5rem;
            width: 28%;
            float: right;
        }

        .register .nav-tabs .nav-link {
            padding: 2%;
            height: 34px;
            font-weight: 600;
            color: #fff;
            border-top-right-radius: 1.5rem;
            border-bottom-right-radius: 1.5rem;
        }

        .register .nav-tabs .nav-link:hover {
            border: none;
        }

        .register .nav-tabs .nav-link.active {
            width: 100px;
            color: #0062cc;
            border: 2px solid #0062cc;
            border-top-left-radius: 1.5rem;
            border-bottom-left-radius: 1.5rem;
        }

        .register-heading {
            text-align: center;
            margin-top: 8%;
            margin-bottom: -15%;
            color: #495057;
        }

        .s-row:hover {
            transition-duration: 0.5s;
            transform: scale(1.1);
        }

        .btnCreate {
            width: 100%;
            margin-top: 20px;
            font-size: 15px;
        }

        .head:hover {
            letter-spacing: 5px;
            transition-duration: 0.2s;
        }
    </style>
</head>

<body>
    <div class="row">
        <div class="col">
            <!-- <div class="display-6 text-center text-info font-weight-bold">Create Custom Object</div> -->
        </div>
    </div>


    <div class="row">
        <div class="col">
            <div class="container register">
                <div class="row">
                    <div class="col-md-3 register-left">
                        <img src="https://image.ibb.co/n7oTvU/logo_white.png" alt="" />
                        <h3 class='head'>Welcome</h3>
                        <p class="head">You are few steps away from Creating your custom object!</p>
                        <input type="submit" name="" value="Custom Objects" /><br />
                    </div>
                    <div class="col-md-9 register-right">


                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="home" role="tabpanel" aria-labelledby="home-tab">
                                <h3 class="register-heading text-info font-weight-bold head">Create Custom Object</h3>
                                <form action="" method="post">
                                    <div class="row register-form">

                                        <!-- first row     -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="text" class="form-control objectName" placeholder="Custom Object Name" value="" />
                                            </div>
                                            <div class="form-group">
                                                <input type="text" class="form-control primaryDisplayPpt" placeholder="Primary Display property" value="" />

                                            </div>



                                        </div>

                                        <!--second row -->
                                        <div class="col-md-6">
                                            <div class="form-group">
                                                <input type="text" class="form-control singularName" placeholder="Singular Name" value="" />
                                            </div>
                                            <div class="form-group">
                                                <input type="text" class="form-control pluralName" placeholder="Plural Name" value="" />
                                            </div>

                                            <!-- submit Button -->
                                        </div>
                                        <div class="row">
                                            <div class="col">
                                                <div class="form-group mt-5">
                                                    <label class="text-info">Properties</label>
                                                </div>
                                            </div>
                                        </div>

                                        <div class="pptContiner">

                                            <div class="row mb-4">
                                                <div class="col">

                                                    <button class="btn btn-outline-success" id='addProperty'>
                                                        +
                                                        add property</button>
                                                </div>
                                            </div>

                                            <div class="pptHTML">

                                            </div>


                                        </div>

                                        <div class="row">
                                            <div class="col">
                                                <div class="h6 text-info mt-5 font-weight-bold">Choose Object You want to associate</div>
                                                <div class="form-check">
                                                    <input class="form-check-input assoCK" type="checkbox" value="CONTACT" id="flexCheckDefault">
                                                    <label class="form-check-label" for="flexCheckDefault">
                                                        Contact
                                                    </label><br>
                                                    <input class="form-check-input assoCK" type="checkbox" value="COMPANY" id="flexCheckDefault">
                                                    <label class="form-check-label" for="flexCheckDefault">
                                                        Company
                                                    </label><br>
                                                    <input class="form-check-input assoCK" type="checkbox" value="DEAL" id="flexCheckDefault">
                                                    <label class="form-check-label" for="flexCheckDefault">
                                                        Deal
                                                    </label><br>
                                                    <input class="form-check-input assoCK" type="checkbox" value="TICKET" id="flexCheckDefault">
                                                    <label class="form-check-label" for="flexCheckDefault">
                                                        Ticket
                                                    </label>
                                                </div>

                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col-5">
                                                <div class="h6 text-info font-weight-bold mt-3">Required properties</div>
                                                <button class="btn btn-outline-info mt-2 showPptBtn">Show Property</button>
                                                <div class="requiredPPTBox ml-3 mt-3">

                                                </div>
                                            </div>
                                        </div>

                                        <div class="row">
                                            <div class="col d-flex justify-content-center">
                                                <input type="submit" class="btnCreate btn btn-outline-success" value="Create" />
                                            </div>
                                        </div>

                                    </div>


                                </form>
                            </div>

                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>

</body>

<script>
    $(document).ready(function() {
        console.log("Working");

        var ppt = "<div class='row mt-3 s-row d-flex justify-content-center'>\
                        <div class='col' id='propertyName'>\
                            <input type='text' id='form12' class='form-control pptName' placeholder='Property Name'/>\
                        </div>\
                        <div class='col' id='labelName'>\
                            <input type='text' id='form12' class='form-control pptlabel' placeholder='Label Name' />\
                        </div>\
                        <div class='col' id='propertyType'>\
                            <select class='form-select pptType' aria-label='Default select example'>\
                                <option selected disabled>Type</option>\
                                <option value='enumeration'>Enumeration</option>\
                                <option value='date'>Date</option>\
                                <option value='string'>String</option>\
                                <option value='number'>Number</option>\
                            </select>\
                        </div>\
                        <div class='col' id='propertyFeildType'>\
                            <select class='form-select pptFeildType' aria-label='Default select example'>\
                            <option selected disabled>FeildType</option>\
                            </select>\
                        </div>\
                        <div class='col'>\
                           <button class='btn btn-outline-danger delPPT' value='XX'>X Delete property</button>\
                        </div>\
                    </div>";

        //FeildTypes
        var enumeration = "\
        <option value='booleancheckbox'>booleancheckbox</option>\
        <option value='checkbox'>checkbox</option>\
        <option value='radio'>radio</option>\
        <option value='select'>select</option>";

        var date = '<option value="date">date</option>';

        var string = "\
        <option value='file'>file</option>\
        <option value='text'>text</option>\
        <option value='textarea'>textarea</option>";

        var number = "<option value='number'>number</option>";

        // var property name
        var property = {
            propertyName: [],
            propertytype: [],
            propertyFeildType: [],
            propertylabel: [],
        };

        var associateObjects = [];

        var requiredProperty = [];

        $('#addProperty').click(function(e) {
            e.preventDefault();
            console.log("clicked");

            $('.pptHTML').append(ppt);

            $('.delPPT').click(function(e) {
                e.preventDefault();
                console.log("Clicked" + this.value);
                $(this).parent().parent().remove();

            });

            $('.pptType').click(function(e) {
                e.preventDefault();
                console.log(this.value);

                if (this.value == 'enumeration') {
                    console.log("this is  enumration");
                    // var vv = $(this).parent().html();
                    // $array
                    $(this).parent().parent().children('#propertyFeildType').children().html(enumeration);

                    // console.log(vv);
                    // $(selected).children();

                } else if (this.value == 'date') {
                    console.log("this is  date");
                    $(this).parent().parent().children('#propertyFeildType').children().html(date);



                } else if (this.value == 'string') {
                    console.log("this is  string");
                    $(this).parent().parent().children('#propertyFeildType').children().html(string);


                } else if (this.value == 'number') {
                    console.log("this is  number");
                    $(this).parent().parent().children('#propertyFeildType').children().html(number);

                }
            });

        });

        $('.btnCreate').click(function(e) {
            e.preventDefault();

            //Store the Indivisual Propety Name
            $('.pptlabel').map(function() {
                property.propertylabel.push(this.value);
                // console.log(this.value);
            }).get();

            //property name
            $('.pptName').map(function() {
                property.propertyName.push(this.value);
                // console.log(this.value);
            }).get();

            //Store the Individual Property Value
            $(".pptType option:selected").map(function() {
                property.propertytype.push(this.value);
                // console.log(this.value);

            }).get();

            //Store the Individual Property Name
            $(".pptFeildType option:selected").map(function() {
                property.propertyFeildType.push(this.value);
                // console.log(this.value);

            }).get();

            //Store the associate object property
            $(".assoCK:checked").map(function() {
                if (associateObjects.includes(this.value)) {} else {
                    associateObjects.push(this.value);
                }

            }).get();

            //Store the associate object property
            $(".requiredValue:checked").map(function() {
                if (requiredProperty.includes(this.value)) {} else {
                    requiredProperty.push(this.value);
                }

            }).get();


            var mergePropertyObject = [];

            for (var i = 0; i < property.propertyFeildType.length; i++) {
                mergePropertyObject.push({
                    name: property.propertyName[i],
                    label: property.propertylabel[i],
                    type: property.propertytype[i],
                    fieldType: property.propertyFeildType[i]
                });
            }

            // var JsonPPT = JSON.stringify(mergePropertyObject);
            $.ajax({
                type: "post",
                url: "https://remote.local.cedcommerce.com/hubspotremote/custom/createcustom?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ",
                data: {
                    "labels": {
                        "singular": $('.singularName').val(),
                        "plural": $('.pluralName').val()
                    },
                    "requiredProperties": requiredProperty,
                    "properties": mergePropertyObject,
                    "associatedObjects": associateObjects,
                    "name": $('.objectName').val(),
                    "primaryDisplayProperty": $('.primaryDisplayPpt').val(),
                    "metaType": "PORTAL_SPECIFIC"
                },
                success: function(response) {
                    console.log("response\n" + response);
                }
            });
            console.log(property);
            console.log(associateObjects);
            console.log(requiredProperty);

        });


        //When user click on required property dropdown will fill with his input properties
        $('.showPptBtn').click(function(e) {
            e.preventDefault();
            console.log("clicked");
            var htm = "";

            $('.pptName').map(function() {
                // htm += "<label>" + this.value + "</label>\
                // <input type='checkbox' value='" + this.value+ "'<br>";
                // console.log(this.value);

                htm += '<div class="form-check">\
                            <input class="form-check-input requiredValue" type="checkbox" value="' + this.value + '" id="requiredPPT">\
                            <label class="form-check-label" for="flexCheckDefault">\
                                ' + this.value + '\
                            </label>\
                       </div>';
            }).get();

            console.log(htm);
            $(".requiredPPTBox").html(htm);


        });
    });
</script>

</html>