<?php
//  echo $data;
//  die;
?>
<!doctype html>
<html>

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <style>
        table {
            /* padding: 10px; */
            border: 2px solid red;
            border-collapse: collapse;
            text-align: center;

        }

        tr:hover {
            transition-duration: 0.7s;
            /* background-color: black; */
            /* color: white; */
            /* border: 3px solid red; */
            transform: scale(1.05);
            border-radius: 2px;
            box-shadow: rgba(50, 50, 93, 0.25) 0px 30px 60px -12px inset, rgba(0, 0, 0, 0.3) 0px 18px 36px -18px inset;

        }

        td:hover {
            transition-duration: 0.7s;
            /* background-color: black; */
            /* color: white; */
            /* border: 3px solid red; */
            transform: scale(1.1);
            border-radius: 10px;
            box-shadow: rgba(50, 50, 93, 0.25) 0px 30px 60px -12px inset, rgba(0, 0, 0, 0.3) 0px 18px 36px -18px inset;

        }

        td {
            border: 2px solid black;
        }
    </style>
</head>

<body>
    <h1 class="text-center text-lead display-5 text-danger">Custom Object Listing</h1>
    <div class="row">
        <div class="col d-flex justify-content-center">
            <button class="btn btn-outline-success mr-2" id="creaProduct"> <a href="http://remote.local.cedcommerce.com/hubspotremote/custom/createcustom?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ" style="text-decoration: none; color:black">Create Custom Object</a></button>
        </div>
    </div>

    <table class="table  table-striped">
        <thead>
            <tr>
                <th class="text-info">ObjectType ID</th>
                <th class="text-info">Object ID</th>
                <th class="text-info">Name</th>
                <th class="text-info">Primary Display Property</th>
                <th class="text-info">Required Propert</th>
                <th class="text-info">Actions</th>
            </tr>
        </thead>
        <tbody>
            <?php echo $data ?>
        </tbody>
    </table>
</body>

</html>