<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Bootstrap CRUD Data Table for Database with Modal Form</title>
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto|Varela+Round">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <style>
        body {
            color: #566787;
            background: #f5f5f5;
            font-family: 'Varela Round', sans-serif;
            font-size: 13px;
        }

        .table-wrapper {
            background: #fff;
            padding: 20px 25px;
            margin: 30px 0;
            border-radius: 3px;
            box-shadow: 0 1px 1px rgba(0, 0, 0, .05);
        }

        .table-title {
            padding-bottom: 15px;
            background: #435d7d;
            color: #fff;
            padding: 16px 30px;
            margin: -20px -25px 10px;
            border-radius: 3px 3px 0 0;
        }

        .table-title h2 {
            margin: 5px 0 0;
            font-size: 24px;
        }

        .table-title .btn-group {
            float: right;
        }

        .table-title .btn {
            color: #fff;
            float: right;
            font-size: 13px;
            border: none;
            min-width: 50px;
            border-radius: 2px;
            border: none;
            outline: none !important;
            margin-left: 10px;
        }

        .table-title .btn i {
            float: left;
            font-size: 21px;
            margin-right: 5px;
        }

        .table-title .btn span {
            float: left;
            margin-top: 2px;
        }

        table.table tr th,
        table.table tr td {
            border-color: #e9e9e9;
            padding: 12px 15px;
            vertical-align: middle;
        }

        table.table tr th:first-child {
            width: 60px;
        }

        table.table tr th:last-child {
            width: 100px;
        }

        table.table-striped tbody tr:nth-of-type(odd) {
            background-color: #fcfcfc;
        }

        table.table-striped.table-hover tbody tr:hover {
            background: #f5f5f5;
        }

        table.table th i {
            font-size: 13px;
            margin: 0 5px;
            cursor: pointer;
        }

        table.table td:last-child i {
            opacity: 0.9;
            font-size: 22px;
            margin: 0 5px;
        }

        table.table td a {
            font-weight: bold;
            color: #566787;
            display: inline-block;
            text-decoration: none;
            outline: none !important;
        }

        table.table td a:hover {
            color: #2196F3;
        }

        table.table td a.edit {
            color: #FFC107;
        }

        table.table td a.delete {
            color: #F44336;
        }

        table.table td i {
            font-size: 19px;
        }

        table.table .avatar {
            border-radius: 50%;
            vertical-align: middle;
            margin-right: 10px;
        }

        .pagination {
            float: right;
            margin: 0 0 5px;
        }

        .pagination li a {
            border: none;
            font-size: 13px;
            min-width: 30px;
            min-height: 30px;
            color: #999;
            margin: 0 2px;
            line-height: 30px;
            border-radius: 2px !important;
            text-align: center;
            padding: 0 6px;
        }

        .pagination li a:hover {
            color: #666;
        }

        .pagination li.active a,
        .pagination li.active a.page-link {
            background: #03A9F4;
        }

        .pagination li.active a:hover {
            background: #0397d6;
        }

        .pagination li.disabled i {
            color: #ccc;
        }

        .pagination li i {
            font-size: 16px;
            padding-top: 6px
        }

        .hint-text {
            float: left;
            margin-top: 10px;
            font-size: 13px;
        }

        /* Custom checkbox */
        .custom-checkbox {
            position: relative;
        }

        .custom-checkbox input[type="checkbox"] {
            opacity: 0;
            position: absolute;
            margin: 5px 0 0 3px;
            z-index: 9;
        }

        .custom-checkbox label:before {
            width: 18px;
            height: 18px;
        }

        .custom-checkbox label:before {
            content: '';
            margin-right: 10px;
            display: inline-block;
            vertical-align: text-top;
            background: white;
            border: 1px solid #bbb;
            border-radius: 2px;
            box-sizing: border-box;
            z-index: 2;
        }

        .custom-checkbox input[type="checkbox"]:checked+label:after {
            content: '';
            position: absolute;
            left: 6px;
            top: 3px;
            width: 6px;
            height: 11px;
            border: solid #000;
            border-width: 0 3px 3px 0;
            transform: inherit;
            z-index: 3;
            transform: rotateZ(45deg);
        }

        .custom-checkbox input[type="checkbox"]:checked+label:before {
            border-color: #03A9F4;
            background: #03A9F4;
        }

        .custom-checkbox input[type="checkbox"]:checked+label:after {
            border-color: #fff;
        }

        .custom-checkbox input[type="checkbox"]:disabled+label:before {
            color: #b8b8b8;
            cursor: auto;
            box-shadow: none;
            background: #ddd;
        }

        /* Modal styles */
        .modal .modal-dialog {
            max-width: 400px;
        }

        .modal .modal-header,
        .modal .modal-body,
        .modal .modal-footer {
            padding: 20px 30px;
        }

        .modal .modal-content {
            border-radius: 3px;
        }

        .modal .modal-footer {
            background: #ecf0f1;
            border-radius: 0 0 3px 3px;
        }

        .modal .modal-title {
            display: inline-block;
        }

        .modal .form-control {
            border-radius: 2px;
            box-shadow: none;
            border-color: #dddddd;
        }

        .modal textarea.form-control {
            resize: vertical;
        }

        .modal .btn {
            border-radius: 2px;
            min-width: 100px;
        }

        .modal form label {
            font-weight: normal;
        }

        button {
            background-color: transparent;
            border-style: none;
            outline: none;
        }

        button:focus {
            border-style: none;
            outline: none;
        }
    </style>

<body>
    <div class="container">
        <div class="table-wrapper">
            <div class="table-title">
                <div class="row">
                    <div class="col-sm-6">
                        <h2>Manage <b>Employees</b></h2>
                    </div>
                    <div class="col-sm-6">
                        <a href="#addEmployeeModal" class="btn btn-success" data-toggle="modal"><i class="material-icons">&#xE147;</i> <span>Create Template</span></a>
                        <a href="#deleteEmployeeModal" class="btn btn-danger" data-toggle="modal"><i class="material-icons">&#xE15C;</i> <span>Delete</span></a>
                    </div>
                </div>
            </div>
            <table class="table table-striped table-hover">
                <thead>
                    <tr>
                        <th>
                            <span class="custom-checkbox">
                                <input type="checkbox" id="selectAll">
                                <label for="selectAll"></label>
                            </span>
                        </th>
                        <th>ID</th>
                        <th>Name</th>
                        <th>Object Type</th>
                        <th>Header</th>
                        <th>Actions</th>
                    </tr>
                </thead>
                <tbody>
                    <?php
                    if (isset($tableData)) {
                        echo $tableData;
                    } else {
                        echo "<tr>Data is not available</tr>";
                    }
                    ?>
                </tbody>
            </table>
            <!-- <div class="clearfix">
                <div class="hint-text">Showing <b>5</b> out of <b>25</b> entries</div>
                <ul class="pagination">
                    <li class="page-item disabled"><a href="#">Previous</a></li>
                    <li class="page-item"><a href="#" class="page-link">1</a></li>
                    <li class="page-item"><a href="#" class="page-link">2</a></li>
                    <li class="page-item active"><a href="#" class="page-link">3</a></li>
                    <li class="page-item"><a href="#" class="page-link">4</a></li>
                    <li class="page-item"><a href="#" class="page-link">5</a></li>
                    <li class="page-item"><a href="#" class="page-link">Next</a></li>
                </ul>
            </div> -->
        </div>
    </div>

    <!-- ADD Modal HTML ****************************************************************-->
    <div id="addEmployeeModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form>
                    <div class="modal-header">
                        <h4 class="modal-title">Create Template</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <div class="form-group">
                            <label>Name</label>
                            <input type="text" class="form-control name">
                        </div>
                        <div class="form-group">
                            <label>Header Template</label>
                            <input type="text" class="form-control headerTemplate">
                        </div>

                        <div class="form-group mt-5">
                            <label>Object Type</label>
                            <select class="ml-3 form-select objectType2" aria-label="Default select example">
                                <option selected disabled>Open this select ObjectType</option>
                                <option value="contacts">Contacts</option>
                                <option value="companies">Companies</option>
                                <option value="deals">Deals</option>
                                <option value="tickets">Tickets</option>
                            </select>
                        </div>
                        <div class="form-group">
                            <label>Token</label>
                            <button class="btn btn-outline-danger mt-2" style="margin-left:45px" id='addProperty'>Add Display Property</button><br>
                            <div class="displayPPT"></div>
                        </div>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                        <input type="submit" class="btn btn-success" id="saveBtn" value="Add">
                    </div>
                </form>
            </div>
        </div>
    </div>
    <!-- Edit Modal HTML   EDITTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTTT -->
    <div id="editEmployeeModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Edit Employee</h4>
                    <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label>Name</label>
                        <input type="text" class="form-control name12" required>
                    </div>
                    <div class="form-group">
                        <label>Header Template</label>
                        <input type="email" class="form-control headerTemplate12" required>
                    </div>
                    <div class="form-group mt-5">
                        <label>Object Type</label>
                        <select class="ml-3 form-select objectType3" aria-label="Default select example">
                            <option value="contacts">Contacts</option>
                            <option value="companies">Companies</option>
                            <option value="deals">Deals</option>
                            <option value="tickets">Tickets</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label>Token</label>
                        <button class="btn btn-outline-danger mt-2" style="margin-left:45px" id='addProperty2'>Add Display Property</button><br>
                        <div class="displayPPT2"></div>
                    </div>
                </div>
                <div class="modal-footer">
                    <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                    <input type="submit" class="btn btn-info" id="updateBtn" value="Save">
                </div>
            </div>
        </div>
    </div>
    <!-- Delete Modal HTML -->
    <div id="deleteEmployeeModal" class="modal fade">
        <div class="modal-dialog">
            <div class="modal-content">
                <form>
                    <div class="modal-header">
                        <h4 class="modal-title">Delete Employee</h4>
                        <button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
                    </div>
                    <div class="modal-body">
                        <p>Are you sure you want to delete these Records?</p>
                        <p class="text-warning"><small>This action cannot be undone.</small></p>
                    </div>
                    <div class="modal-footer">
                        <input type="button" class="btn btn-default" data-dismiss="modal" value="Cancel">
                        <input type="submit" class="btn btn-danger" value="Delete">
                    </div>
                </form>
            </div>
        </div>
    </div>
</body>

</html>

<script>
    $(document).ready(function() {
        var ppt = "<div class='row mt-3 s-row d-flex justify-content-center mt-5'>\
                        <div class='col' class='propertyName'>\
                            <input type='text' id='form12' class='form-control pptName' placeholder='Name'/>\
                        </div>\
                        <div class='col' class='labelName'>\
                            <input type='text' id='form12' class='form-control pptlabel' placeholder='Label' />\
                        </div>\
                        <div class='col mt-2' class='propertyType'>\
                            <select class='form-select pptType' aria-label='Default select example'>\
                                <option selected disabled>Type</option>\
                                <option value='string'>string</option>\
                                <option value='number'>number</option>\
                                <option value='date'>date</option>\
                            </select>\
                        </div>\
                        <div class='col-3'>\
                           <button  class='btn btn-outline-danger delPPT mb-4' style='margin-left:-20px' value='XX'>X Delete</button>\
                        </div>\
                    </div>";
        var editID = "";
        $('#addProperty').click(function(e) {
            e.preventDefault();
            $('.displayPPT').append(ppt);
        });

        $('#addProperty2').click(function(e) {
            e.preventDefault();
            $('.displayPPT2').append(ppt);
        });

        $(this).on("click", ".delPPT", function() {
            $(this).parent().parent().remove();
        });

        $("#saveBtn").click(function(e) {
            e.preventDefault();
            var pptName = [];
            var pptLabel = [];
            var pptType = [];
            var token = [];

            var PostData = {
                name: "",
                objectType: "",
                headerTemplate: "",
                tokens: [],
            };

            $(".pptName").map(function() {
                // var ppt = ".property2" + this.value + ":checked";
                console.log(this.value);
                pptName.push(this.value);

            }).get();
            $(".pptlabel").map(function() {
                // var ppt = ".property2" + this.value + ":checked";
                console.log(this.value);
                pptLabel.push(this.value);


            }).get();
            $(".pptType option:selected").map(function() {
                pptType.push(this.value);
                console.log(this.value);

            }).get();

            for (var i = 0; i < pptName.length; i++) {
                PostData.tokens.push({
                    "name": pptName[i],
                    "label": pptLabel[i],
                    "type": pptType[i]
                });
            }


            //Name save 
            PostData.name = $('.name').val();
            PostData.headerTemplate = $('.headerTemplate').val();
            PostData.objectType = $(".objectType2 option:selected").val();
            console.log(PostData);

            $.ajax({
                type: "post",
                url: "https://remote.local.cedcommerce.com/hubspotremote/timeline/createTemplate?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ",
                data: {
                    'PostData': PostData
                },
                success: function(response) {
                    console.log(response)
                }
            });
        });


        //Update Button
        $("#updateBtn").click(function(e) {
            e.preventDefault();
            e.preventDefault();
            var pptName = [];
            var pptLabel = [];
            var pptType = [];
            var token = [];

            var PostData = {
                id: "",
                name: "",
                objectType: "",
                headerTemplate: "",
                tokens: [],
            };

            $(".pptName").map(function() {
                // var ppt = ".property2" + this.value + ":checked";
                console.log(this.value);
                pptName.push(this.value);

            }).get();
            $(".pptlabel").map(function() {
                // var ppt = ".property2" + this.value + ":checked";
                console.log(this.value);
                pptLabel.push(this.value);


            }).get();
            $(".pptType option:selected").map(function() {
                pptType.push(this.value);
                console.log(this.value);

            }).get();

            for (var i = 0; i < pptName.length; i++) {
                PostData.tokens.push({
                    "name": pptName[i],
                    "label": pptLabel[i],
                    "type": pptType[i]
                });
            }

            PostData.id = editID;


            //Name save 
            PostData.name = $('.name12').val();
            PostData.headerTemplate = $('.headerTemplate12').val();
            PostData.objectType = $(".objectType3 option:selected").val();
            console.log(PostData);

            $.ajax({
                type: "post",
                url: "https://remote.local.cedcommerce.com/hubspotremote/timeline/updateTemplate?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ",
                data: {
                    'PostData': PostData,
                    'id': editID
                },
                success: function(response) {
                    console.log(response)
                }
            });
        });

        $(".editData").click(function(e) {
            e.preventDefault();
            console.log(this.value);
            editID = this.value;
            $.ajax({
                type: "post",
                url: "https://remote.local.cedcommerce.com/hubspotremote/timeline/getCustomTemplateData?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ",
                data: {
                    "id": this.value
                },
                success: function(response) {
                    console.log(response);
                    var data = JSON.parse(response);
                    console.log(data);
                    var newPPT;
                    $('.name12').val(data.name);
                    $('.headerTemplate12').val(data.headerTemplate);

                    // foreach()
                    //TOKEN LISTING left out
                    // $(".objectType option:selected").val(PostData.objectType);
                    if (data.tokens.length !== 0) {
                        $.each(data.tokens, function(indexInArray, valueOfElement) {
                            console.log(valueOfElement);
                            newPPT += "<div class='row mt-3 s-row d-flex justify-content-center mt-5'>\
                        <div class='col' class='propertyName'>\
                            <input type='text' id='form12' class='form-control pptName' value=" + valueOfElement.name + " placeholder='Name'/>\
                        </div>\
                        <div class='col' class='labelName'>\
                            <input type='text' id='form12' value=" + valueOfElement.label + " class='form-control pptlabel' placeholder='Label' />\
                        </div>\
                        <div class='col mt-2' class='propertyType'>\
                            <select class='form-select pptType' aria-label='Default select example'>\
                                <option selected disabled>Type</option>\
                                <option value='string'>string</option>\
                                <option value='number'>number</option>\
                                <option value='date'>date</option>\
                                <option value='textarea'>textarea</option>\
                            </select>\
                        </div>\
                        <div class='col-3'>\
                           <button  class='btn btn-outline-danger delPPT mb-4' style='margin-left:-20px' value='XX'>X Delete</button>\
                        </div>\
                    </div>";

                        });


                        $('.displayPPT2').html(newPPT);

                        console.log(newPPT);
                    }
                }
            });
        });

    });
</script>