<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-gH2yIJqKdNHPEq0n4Mqa/HGKIhSkIHeL5AyhkYV8i59U5AR6csBvApHHNl/vI1Bx" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
    <title>Document</title>
</head>
<style>
    #searchBar {
        padding: 5px 15px;
        outline: none;
        border-radius: 10px;
        border: 2px solid black;
        font-family: 'Courier New', Courier;
        color: green;
        font-size: 10px;
        text-align: center;
    }

    #searchBar:focus {
        color: brown;
    }

    #searchBar:hover {
        transition-duration: 1s;
        border-radius: 0px;
    }

    select option {
        border: 1px solid steelblue;
        margin-top: 2px;
        text-align: center;
        border-radius: 5px;
    }

    select option:hover {
        transition-duration: 0.3s;
        background-color: steelblue;
        color: white;
        letter-spacing: 3px;
    }

    .assoRadio:active {
        background: black;
    }

    /* img{
        height: 100px;
        width: 100px;
        margin-left: 15%;
        margin-top: 10%;
     } */
</style>

<body>

    <div class="h1 text-center text-primary">Custom Object Assocaiton</div>

    <div class="row">
        <div class="col d-flex justify-content-center message">

        </div>
    </div>

    <div class="row mt-5  d-flex justify-content-center mt-5">

        <div class="col">
            <div class="input-group d-flex justify-content-center">
                <input type="search" class="" placeholder="Search Custom Object" id="searchBar" aria-label="Search" aria-describedby="search-addon" />
            </div>
            <select class="mt-1 form-select form-select-sm selectForm" size="10" id="optionbar" aria-label="size 10 select example">\
            </select>
        </div>

        <div class="col-3">
            <!-- <img class='img-thumbnail' src="https://cdn-icons-png.flaticon.com/512/25/25385.png" alt="association"> -->
            <!-- <div class="h6 text-center mt-5 text-info">Assocaiton From Custom Object to Standered and Custom Object</div> -->
            <div class="option"></div>
            <div class="assobt">

            </div>

        </div>

        <div class="col">
            <select class="mt-4 form-select form-select-sm selectForm" size="10" id="toObjects" aria-label="size 10 select example">\
        </div>


    </div>

    <div class="row mt-5 d-flex justify-content-center mt-5">
        <div class="col">
            <button class="btn btn-outline-success">Associate</button>
        </div>
    </div>



</body>








<script>
    $(document).ready(function() {
        var CustomObjectData = [];
        var ToObjectCustomObjectData = [
            'Contact',
            'Ticket',
            'Company',
            'Deal'
        ];

        var toObjectStr = '<option value="Contact">Contact</option>\
                         <option value="Company">Company</option>\
                         <option value="Deal">Deal</option>\
                         <option value="Ticket">Ticket</option>';
        var mainObjectName = '';
        // console.log("sd");
        //Ajax call to get all the data of custom object
        $.ajax({
            type: "post",
            url: "https://remote.local.cedcommerce.com/hubspotremote/crud/getCustomObjectData?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ",
            success: function(response) {
                var jsondata = JSON.parse(response);
                CustomObjectData = jsondata;
                console.log(jsondata);
            }
        });



        //Live Search
        $("#searchBar").keyup(function() {
            var str = "";
            for (var i = 0; i < CustomObjectData.results.length; i++) {

                if (CustomObjectData.results[i].name.match(this.value)) {
                    str += "<option value=" + CustomObjectData.results[i].objectTypeId + ">" + CustomObjectData.results[i].name + "</option>";
                    toObjectStr += "<option value=" + CustomObjectData.results[i].objectTypeId + ">" + CustomObjectData.results[i].name + "</option>";
                }
            }

            $("#optionbar").html(str);


        });

        //associate button
        $(this).on('click', '#assoBtn', function() {
            // $object
            var fromObjectName = $('#optionbar option:selected').text();
            var toObjectName = $('#toObjects option:selected').text();
            var fromObjectTypeID = $('#optionbar option:selected').val();
            var toObjectType = $('#toObjects').val();
            var name = fromObjectName + '_to_' + toObjectName;
            console.log(name);
            // console.log($('#toObjects').val());

            var obj = {
                "fromObjectTypeId": fromObjectTypeID,
                "toObjectTypeId": toObjectType,
                "name": name
            };

            $.ajax({
                type: "post",
                url: "",
                data: obj,
                success: function(response) {
                    var jsonData = JSON.parse(response);
                    console.log(jsonData);
                    if (jsonData.message) {

                        var warnignMSG = '<div class="alert alert-warning" role="alert">\
                        ' + jsonData.message + '\
                        jsonData.message          </div>';
                        $('.message').html(warnignMSG);
                    } else {
                        var sucessMSG = '<div class="alert alert-success" role="alert">\
                        Association Successful\
                        jsonData.message          </div>';
                        $('.message').html(sucessMSG);
                    }

                }
            });
        });


        //Remove association
        $(this).on('click', '#RemoveassoBtn', function() {
            console.log('removeAsso');

            var unquieID = $('#toObjects').val();
            var ObjectTypeID = $('#optionbar option:selected').val();

            $.ajax({
                type: "post",
                url: "https://remote.local.cedcommerce.com/hubspotremote/asso/removeAssoCustomObj?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ",
                data: {
                    "objectType": ObjectTypeID,
                    "id": unquieID
                },
                success: function(response) {
                    console.log(response);
                    if (response == 1) {
                        alert("Association removed Successfully");
                    }
                }
            });

        });


        $('#optionbar').click(function(e) {
            e.preventDefault();
            $('.option').html("<div class='form-check ml-5 mt-5'>\
                                <input class='form-check-input assoRadio' id='createAsso' type='radio' name='flexRadioDefault' id='flexRadioDefault1'>\
                                <label class='form-check-label text-success' for='flexRadioDefault1'>\
                                    Create\
                                </label><br>\
                                <input class='form-check-input assoRadio' id='removeAsso' type='radio' name='flexRadioDefault' id='flexRadioDefault2'>\
                                <label class='form-check-label text-danger' for='flexRadioDefault2'>\
                                    Remove\
                                </label>\
                            </div>");

            $('#createAsso').click(function(e) {
                e.preventDefault();
                $("#toObjects").html(toObjectStr);
                $('.assobt').html('<button class="btn btn-outline-success ml-5 mt-5" id="assoBtn">Create Associate</button>');


            });

            $('#removeAsso').click(function(e) {
                e.preventDefault();
                $('.assobt').html('<button class="btn btn-outline-success ml-5 mt-5" id="RemoveassoBtn">Remove Associate</button>');
                var fromObjectTypeID = $('#optionbar option:selected').val();
                var str2 = '';
                $.ajax({
                    type: "post",
                    data: {
                        "schemaID": fromObjectTypeID
                    },
                    url: "https://remote.local.cedcommerce.com/hubspotremote/asso/getExistingSchemaData?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ",
                    success: function(response) {
                        // console.log(response);
                        var jsonData = JSON.parse(response);
                        console.log(jsonData);
                        // for($jso)
                        $.each(jsonData.associations, function(key, value) {
                            console.log(value)
                            if (value.fromObjectTypeId.length > 5) {

                                str2 += "<option value=" + value.id + ">" + value.name + "</option>";
                            }

                        });
                        $("#toObjects").html(str2);


                    }
                });

            });
            // mainObjectName = $(this).text();

        });

    });
</script>

</html>