<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>

</head>

<body>
    <div class="h1 text-left text-primary"><b>Testing</b></div>

    <div class="row">
        <div class="col">
            <div class="display-6 text-center text-danger mt-3"><b>Search Fetaure</b></div>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-5">
        <div class="col-6">
            <div class="input-group">
                <input type="search" class="form-control rounded" placeholder="Search Contact" id="searchBar" aria-label="Search" aria-describedby="search-addon" />
                <!-- <button type="button" class="btn btn-outline-primary">search</button> -->
            </div>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-3">
        <div class="col">
            <select class="form-select form-select-sm selectForm" size="10" id="optionbar" aria-label="size 10 select example">\
            </select>
        </div>
    </div>

    <div class="row">
        <div class="col">
            <div class="display-6 text-center text-danger mt-3"><b>Common Method for Ajax call</b></div>
        </div>
    </div>

    <div class="row d-flex justify-content-center mt-3">
        <div class="col d-flex justify-content-center mt-3">
            <button class="btn btn-outline-info" id="ajaxcall">Call Ajax</button>
        </div>
    </div>

</body>

<script>
    $(document).ready(function() {


        var dataa;

        function CallAjaxx(RequestType, Baseurl, jsondata = 'data') {
            $.ajax({
                type: RequestType,
                async: false,
                url: Baseurl,
                data: jsondata,
                success: function(response) {
                    dataa = response;
                    console.log("In ajax call ======>" + dataa);
                }
            });
            return dataa;

        }

        $("#ajaxcall").click(function(e) {
            e.preventDefault();
            // console.log("working");
            var type = "post";
            var url = "https://remote.local.cedcommerce.com/hubspotremote/asso/testing2?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ";
            var data = 'data';
            var response = CallAjaxx(type, url, data);
            console.log("Out of the ajax call ======>" + response);
            // $.ajax({
            //     type: "post",
            //     url: "https://remote.local.cedcommerce.com/hubspotremote/asso/testing2?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ",
            //     data: {
            //         'data':'data'
            //     },
            //     success: function (response) {
            //         console.log(response);
            //     }
            // });
        });


        console.log("working");
        var names = [];
        $.ajax({
            type: "post",
            url: "https://remote.local.cedcommerce.com/hubspotremote/asso/testing?bearer=eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJ1c2VyX2lkIjoiNjI2YmNjMzc2NzM0MTkzZmQ0NTA0MWI5Iiwicm9sZSI6ImFkbWluIiwiZXhwIjoxNjg4NjM2MTE1LCJpc3MiOiJodHRwczpcL1wvYXBwcy5jZWRjb21tZXJjZS5jb20iLCJ0b2tlbl9pZCI6IjYyYzU1NzUzODBjMDYwNTA5MjA2MTVjMiJ9.i45WyHgJ3b11ntGWMGuiNMUri6ezbnALFpFoZkhS2KHGbNA0xge2R6AR-Dsd1U-Gdcv5E9nrQKa3sEh_k7SGA_V4_FGAmFuJUQ5lrLoFpj9oaCc0qSb5A7hf3TY592SozFp-jKRxPlVSWqLhFghWTvcVLV-S_8VfhtSkbretnDY00MCJFaZmTboZkv-FYwHUQM2u1GNsYQAegXL8lHDtz3d9vw1d_t24eZYcvlBlAU1gRQyJQNqaqVThgGdHEvqmyYB2iEsk3LgI8rcxdBEBFYHFJMCfL05BlZ6Ht55d0d5gku-_tGK9cnPz2EVDfQ9OlaQmTrxl2zkTC6Z4G56zIQ",
            data: {
                'SearchData': this.value
            },
            success: function(response) {
                var jsonData = JSON.parse(response);
                // for (var i = 0; i < jsonData.results.length; i++) {
                //     names.push(jsonData.results[i].properties.firstname);
                // }
                names = jsonData;

                // console.log(names);

            }
            // $().search(searcher);
        });

        $("#searchBar").keyup(function() {
            // console.log(this.value);
            // var result = names.includes(this.value);
            // console.log(result);
            var str = "";
            for (var i = 0; i < names.results.length; i++) {


                if (names.results[i].properties.firstname.match(this.value)) {
                    str += "<option value=" + names.results[i].id + ">" + names.results[i].properties.firstname + "</option>";
                }
            }

            // console.log(str);
            $("#optionbar").html(str);

        });
    });
</script>

</html>